@startuml

actor User #blue
User [#blue]-> userComputer
userComputer [#blue]-> userInterface: action

box "server"#LightBlue
userInterface [#blue]-> controller: REST request
controller [#blue]-> converter
converter [#blue]-> service : convert
service [#blue]-> contactDao


database DB #green

contactDao [#blue]-> DB: request
DB [#green]-> contactDao: response
contactDao [#green]-> service
service [#green]-> converter: convert
converter [#green]-> controller
end box

controller [#green]-> userInterface: REST response
userInterface [#green]-> userComputer
userComputer [#green]-> User
@enduml